languageCode: en-us
title: Andi Skrgat blog
baseURL: https://as51340.github.io/blog/

title: Andi Skrgat
paginate: 5
theme: charlolamode

menu:
    main:
        - name: About me
          url: /about/
          weight: 30
        - name: Engineering
          url: /engineering/
          weight: 20
        - name: Football
          url: /football/
          weight: 20

params:
    author: Andi Skrgat
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Let the improvement of yourself keep you so busy that you have no time to criticize others.
        description: |

          Hello, I am Andi Skrgat and I write about various topics interesting to me, mostly related to software engineering. The main reason for writing is the fact that it helps me to understand the topic better and not forget it. I hope you will find something useful here.
        # imageWidth: 120
        # imageHeight: 120
        # buttons:
        #    - name: Don't click me
        #      url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/as51340"
        - name: linkedin
          url: "https://www.linkedin.com/in/andi-skrgat-658b471b8/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true


